project:
  type: website
  output-dir: docs

website:
  title: "TIL"
  favicon: favicon.png
  navbar:
    left:
      - tils.qmd
      - dv.qmd

  page-footer: "Site by [Sharon Howard](https://sharonhoward.org)"
  
  
format:
  html:
    theme:
      - united
      - brand
    css: styles.css
    toc: true



date-format: "D MMMM YYYY"



freeze: auto

