---
title: "multiple scales in a ggplot with ggnewscale"
author: "Sharon Howard"
date: "2025-06-30"
categories: [ggplot, scales]
slug: til-ggplot-multiple-scales-ggnewscale-20250630
execute:
  warning: false
  message: false
---

## Includes

```{r}
source(here::here('R/shared.R'))
```

## Notes

-  package docs example as i haven't thought up anything for this 
 




## Example

```{r}
library(ggnewscale) 
 
# Equivalent to melt(volcano), but we don't want to depend on reshape2 
topography <- expand.grid(x = 1:nrow(volcano), 
                          y = 1:ncol(volcano)) 
topography$z <- c(volcano) 
 
# point measurements of something at a few locations 
measurements <- data.frame(x = runif(30, 1, 80), 
                           y = runif(30, 1, 60), 
                           thing = rnorm(30)) 
 
ggplot(mapping = aes(x, y)) + 
  geom_contour(data = topography, aes(z = z, color = after_stat(level))) + 
  # Color scale for topography 
  scale_color_viridis_c(option = "D") + 
  # geoms below will use another color scale 
  new_scale_color() + 
  geom_point(data = measurements, size = 3, aes(color = thing)) + 
  # Color scale applied to geoms added after new_scale_color() 
  scale_color_viridis_c(option = "A") 

```


## Resources

* [https://eliocamp.github.io/ggnewscale/index.html](https://eliocamp.github.io/ggnewscale/index.html)

```{r}
#| include: false
# atb/atb/_stuff/am_writing_new_project/blogposts/2022-08-25-encoding-alice-thorntons-books.Rmd:447 
 

```
